import json
import os
import urllib.request
from xml.sax.saxutils import escape


API_URL = "https://api.github.com/graphql"
USERNAME = os.getenv("USER_NAME", "tanvir-cpp")
TOKEN = os.getenv("GH_TOKEN") or os.getenv("GITHUB_TOKEN") or os.getenv("ACCESS_TOKEN")

QUERY = """
query ($login: String!) {
  user(login: $login) {
    name
    login
    bio
        location
        url
    followers { totalCount }
    repositories(ownerAffiliations: OWNER, first: 100, privacy: PUBLIC) {
      totalCount
      nodes { stargazerCount }
    }
    contributionsCollection { contributionCalendar { totalContributions } }
  }
}
"""

ASCII_ART = [
    "             .---.            ",
    "            /     |",
    "           /  .-.  |",
    "          |  /   \\\\  |",
    "          | |  .-. | |",
    "          | | (   )| |",
    "          | |  `-' | |",
    "          |  \\\\   /  |",
    "           \\\\  `-'  /",
    "            `-----'",
    "       .--------------.",
    "      |  ASCII PROFILE  |",
    "     /__________________\\\\",
]


def fetch_profile():
    if not TOKEN:
        raise RuntimeError("GH_TOKEN, GITHUB_TOKEN, or ACCESS_TOKEN is required")

    payload = json.dumps({"query": QUERY, "variables": {"login": USERNAME}}).encode()
    request = urllib.request.Request(
        API_URL,
        data=payload,
        headers={
            "Accept": "application/json",
            "Authorization": f"Bearer {TOKEN}",
            "Content-Type": "application/json",
            "User-Agent": "tanvir-cpp-readme-generator",
        },
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        result = json.load(response)

    if result.get("errors"):
        messages = "; ".join(error.get("message", "Unknown GraphQL error") for error in result["errors"])
        raise RuntimeError(messages)
    profile = result.get("data", {}).get("user")
    if not profile:
        raise RuntimeError(f"GitHub user not found: {USERNAME}")
    return profile


def svg_text(x, y, value, color="#c9d1d9", size=16):
    return (
        f'<text x="{x}" y="{y}" fill="{color}" '
        f'font-family="Consolas, Menlo, monospace" font-size="{size}" '
        f'xml:space="preserve">{escape(str(value))}</text>'
    )


def build_svg(profile):
    repositories = profile["repositories"]
    stars = sum(repository["stargazerCount"] for repository in repositories["nodes"])
    contributions = profile["contributionsCollection"]["contributionCalendar"]["totalContributions"]
    display_name = profile.get("name") or profile["login"]
    location = profile.get("location") or "The internet"
    bio = profile.get("bio") or "Software developer and open-source contributor."
    lines = [
        (f"- {display_name} -", "#58a6ff"),
        (f"  @{profile['login']}", "#c9d1d9"),
        (f"  {bio}", "#c9d1d9"),
        ("", "#c9d1d9"),
        (f"  Location: {location}", "#ffa657"),
        (f"  GitHub:  github.com/{profile['login']}", "#ffa657"),
        ("", "#c9d1d9"),
        ("  GitHub Stats", "#58a6ff"),
        (f"  Repositories: {repositories['totalCount']:,}", "#79c0ff"),
        (f"  Stars:        {stars:,}", "#79c0ff"),
        (f"  Contributions: {contributions:,}", "#79c0ff"),
        (f"  Followers:    {profile['followers']['totalCount']:,}", "#79c0ff"),
    ]
    art = "".join(svg_text(28, 42 + index * 19, line) for index, line in enumerate(ASCII_ART))
    right = "".join(svg_text(535, 185 + index * 25, value, color) for index, (value, color) in enumerate(lines))
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1125" height="536" viewBox="0 0 1125 536" role="img" aria-label="ASCII GitHub profile card for {escape(profile['login'])}">
  <rect width="1124" height="535" rx="8" fill="#0d1117" stroke="#30363d"/>
  <g font-weight="400">{art}{right}</g>
</svg>
'''


def build_readme(profile):
    return f"""# {profile.get('name') or profile['login']}

<p align="center">
  <img src="https://raw.githubusercontent.com/{profile['login']}/{profile['login']}/main/dark_mode.svg" alt="ASCII GitHub profile card for {profile['login']}">
</p>

This profile card is generated by [generate_readme.py](https://github.com/{profile['login']}/{profile['login']}/blob/main/generate_readme.py).

Rendering techniques were adapted from the open-source ASCII ecosystem: [chafa](https://github.com/hpjansson/chafa) (fill/structure symbol split), [AAlib](https://aa-project.sourceforge.net/aalib/) (subcell brightness matching), [Acerola's ASCII shader](https://github.com/GarrettGunnell/AcerolaFX) (edge direction voting), and [jp2a](https://github.com/Talinx/jp2a) (directional edge glyphs).
"""


def main():
    profile = fetch_profile()
    with open("dark_mode.svg", "w", encoding="utf-8", newline="\n") as svg:
        svg.write(build_svg(profile))
    with open("README.md", "w", encoding="utf-8", newline="\n") as readme:
        readme.write(build_readme(profile))
    print(f"README updated for @{profile['login']}")


if __name__ == "__main__":
    main()
